---
title: "EDS 215 - Exercise 1"
author: "Alex Vand"
date: "2021-08-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

- `~/` home folder
    - `~/Documents/` documents folder
        - `~/Documents/Blue_Shield_of_Ca/` insurance folder
            - `insurance_card.pdf` pdf of insurance card
            - `summary_benefits.pdf` pdf of summary benefits
        - `~/Documents/Bren/` random Bren forms and documents
            - `alexvand24.github.io` github repo
            - `unofficial_transcript.pdf` pdf of undergrad transcript
        - `~/Documents/EDS_21[2,4,5]/` MEDS various summer classes using indexing
            - `day[1-5]` R projects
            - `evals.docx` document for ESCII evaluations
            - `sampledata` sample data folder
            - `10min-loop.R.txt` txt file that can act as R script
            - `dist` folder for installed applications
            - `eds215-frew` R project for this assignment
            - `shell-lesson-data` data folder
        - `~/Documents/EDS_221/` MEDS summer class
            - `brown-bear.R` R script
            - `eds212-day[1-9]-interactive` R project
            - `eds212-day[1-9]-activities` R project
            - `noodleturtle` R project
            - `fiddler-crab-sizes` R project
        - `~/Documents/'My Music'/` empty music folder
        - `~/Documents/'My Pictures'/` empty pictures folder
        - `~/Documents/'My Video'/` empty video folder
        - `~/Documents/R/` empty R folder
        - `~/Documents/desktop.ini/` determines folder display



